# Generated by Django 4.0 on 2023-02-27 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(null=True)),
                ('quantity', models.CharField(max_length=3, null=True)),
                ('amount', models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Receipts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server', models.CharField(max_length=10, null=True)),
                ('total_amount', models.CharField(max_length=10, null=True)),
                ('items', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Receipts.items')),
            ],
        ),
    ]
