# Generated by Django 4.0 on 2023-02-27 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Receipts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipts',
            name='receipt_number',
            field=models.CharField(max_length=6, null=True),
        ),
    ]
