# Generated by Django 4.0 on 2023-02-27 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0007_account_username_delete_username'),
        ('Receipts', '0002_receipts_receipt_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceiptDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_number', models.CharField(max_length=6, null=True)),
                ('server', models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='receipts',
            name='receipt_number',
        ),
        migrations.RemoveField(
            model_name='receipts',
            name='server',
        ),
        migrations.RemoveField(
            model_name='receipts',
            name='total_amount',
        ),
        migrations.AddField(
            model_name='receipts',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='Authentication.account'),
        ),
        migrations.AlterField(
            model_name='receipts',
            name='items',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Receipts.items'),
        ),
        migrations.AddField(
            model_name='receipts',
            name='details',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='Receipts.receiptdetails'),
        ),
    ]
