# Generated by Django 4.0 on 2023-02-27 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Receipts', '0003_receiptdetails_remove_receipts_receipt_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receipts',
            name='user',
        ),
    ]
