# Generated by Django 4.0 on 2023-02-27 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Receipts', '0004_remove_receipts_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receipts',
            old_name='details',
            new_name='receipt_details',
        ),
    ]
