# Generated by Django 4.0 on 2023-02-27 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Receipts', '0006_remove_receipts_receipt_details_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receipts',
            name='items',
        ),
        migrations.AddField(
            model_name='items',
            name='receipt',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Receipts.receipts'),
        ),
    ]
