# Generated by Django 4.0 on 2023-02-27 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Receipts', '0008_receiptdetails_remove_items_receipt_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receipts',
            name='items',
        ),
        migrations.AddField(
            model_name='receipts',
            name='items',
            field=models.ManyToManyField(null=True, to='Receipts.Items'),
        ),
    ]
