# Generated by Django 4.0 on 2023-02-27 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Receipts', '0009_remove_receipts_items_receipts_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receipts',
            name='receipt_details',
        ),
        migrations.AddField(
            model_name='receipts',
            name='receipt_number',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='receipts',
            name='server',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.DeleteModel(
            name='ReceiptDetails',
        ),
    ]
