# Generated by Django 4.0 on 2023-02-27 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Receipts', '0011_remove_receipts_items_items_receipt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items',
            name='receipt',
        ),
        migrations.AddField(
            model_name='receipts',
            name='items',
            field=models.ManyToManyField(to='Receipts.Items'),
        ),
    ]
