# Generated by Django 4.0 on 2023-02-28 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Receipts', '0015_receipts_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receipts',
            name='customer',
        ),
    ]
