# Generated by Django 4.0 on 2023-02-28 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Receipts', '0023_rename_customer_receipts_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receipts',
            old_name='user',
            new_name='customer',
        ),
    ]
