# Generated by Django 4.0 on 2023-02-28 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Receipts', '0024_rename_user_receipts_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipts',
            name='customer',
            field=models.IntegerField(max_length=10, null=True),
        ),
    ]
