# Generated by Django 4.0 on 2023-02-28 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Receipts', '0025_alter_receipts_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receipts',
            old_name='customer',
            new_name='customer_id',
        ),
        migrations.AddField(
            model_name='receipts',
            name='customer_name',
            field=models.IntegerField(max_length=10, null=True),
        ),
    ]
