# Generated by Django 4.0 on 2023-02-28 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Receipts', '0026_rename_customer_receipts_customer_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipts',
            name='customer_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='receipts',
            name='customer_name',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
