# Generated by Django 4.0 on 2023-02-28 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TranscationRecords', '0001_initial'),
        ('Receipts', '0030_alter_items_amount_alter_items_quantity'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Items',
            new_name='Item',
        ),
        migrations.RenameModel(
            old_name='Receipts',
            new_name='Receipt',
        ),
    ]
