# Generated by Django 4.0 on 2023-03-05 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Receipts', '0032_alter_receipt_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='total',
            field=models.IntegerField(null=True),
        ),
    ]
