# Generated by Django 4.0 on 2023-03-05 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Receipts', '0033_receipt_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='server_name',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
