# Generated by Django 4.0 on 2023-04-30 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Receipts', '0035_receipt_day_receipt_overseer_receipt_published_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='name',
            new_name='item_name',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='amount',
            new_name='item_number',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='quantity',
            new_name='item_price',
        ),
    ]
