# Generated by Django 4.0 on 2023-04-30 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Receipts', '0036_rename_name_item_item_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='item_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='item_price',
            new_name='price',
        ),
    ]
