# Generated by Django 4.0 on 2023-04-30 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Receipts', '0037_rename_item_name_item_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receipt',
            old_name='customer_id',
            new_name='customer',
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='customer_name',
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='day',
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='overseer',
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='published',
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='server',
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='week',
        ),
        migrations.AddField(
            model_name='receipt',
            name='store_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
