# Generated by Django 4.0 on 2023-04-30 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Receipts', '0038_rename_customer_id_receipt_customer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='customer',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
