# Generated by Django 4.0 on 2023-05-01 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Receipts', '0041_alter_receipt_receipt_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.CharField(max_length=200, null=True)),
                ('receipt', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Receipts.receipt')),
            ],
        ),
    ]
