# Generated by Django 4.0 on 2023-05-01 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Receipts', '0042_statement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statement',
            name='client',
            field=models.TextField(null=True),
        ),
    ]
