# Generated by Django 4.0 on 2023-05-01 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Receipts', '0043_alter_statement_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='statement',
            name='code',
            field=models.IntegerField(null=True),
        ),
    ]
