# Generated by Django 4.0 on 2023-05-03 16:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Receipts', '0045_receipt_server'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='published',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
