# Generated by Django 4.0 on 2023-05-03 16:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Receipts', '0046_receipt_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='published',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
