# Generated by Django 4.0 on 2023-05-03 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Receipts', '0047_alter_receipt_published'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receipt',
            name='published',
        ),
    ]
