# Generated by Django 4.0 on 2023-05-11 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Receipts', '0048_remove_receipt_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='till_number',
            field=models.IntegerField(null=True),
        ),
    ]
