# Generated by Django 4.0 on 2023-05-11 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Receipts', '0049_receipt_till_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Statement',
        ),
    ]
