# Generated by Django 4.0 on 2023-01-13 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0003_phonenumber_is_active_phonenumber_is_admin_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PhoneNumber',
        ),
    ]
