# Generated by Django 4.0 on 2023-01-23 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0004_delete_phonenumber'),
    ]

    operations = [
        migrations.CreateModel(
            name='Username',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=1000)),
                ('code', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Authentication.code')),
            ],
        ),
    ]
