# Generated by Django 4.0 on 2023-01-26 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0005_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='username',
            name='code',
        ),
        migrations.AddField(
            model_name='username',
            name='user',
            field=models.OneToOneField(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='Authentication.account'),
        ),
    ]
